swagger: "2.0"

info:
  version: '1'
  description: "Chkl Self-Learning"
  title: "Self-Learning"
externalDocs:
  description: "Github"
  url: "https://github.com/MechFroG88/Self-learning"
host:
  mechfrog88.ddns.net
schemes:
- "http"
- "https"
paths:
  /user:
    post:
      tags:
      - "Users"
      summary: "Create new user"
      parameters:
      - in: "body"
        name: "Body"
        description: "Create new user"
        schema:
          type: "object"
          properties:
            id:
              type: "string"
              example: "150142"
            cn_name:
              type: "string"
              example: "常常"
            type:
              type: "integer"
              example: 1
            ic:
              type: "string"
              example: "123456-78-1234"
            gender:
              type: "string"
              example: "男"
            class_id:
              type: "integer"
              example: 1

      responses:
        200:
          description: "Successful operation"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"

    get:
      tags:
      - "Users"
      summary: "Returns current user data"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "object"
            properties:
                id:
                  type: "string"
                  example: "140123"
                cn_name:
                  type: "string"
                  example: "和恶"
                class:
                  type: "string"
                  example: "高三理忠"
                gender:
                  type: "string"
                  example: "男"
                type:
                  type: "integer"
                  example: 1
                is_submit:
                  type: "boolean"
                  example : 0
                lessons:
                    type: "object"
                    properties:
                      1:
                        type: "integer"
                        example: "2"
                forced_lessons:
                    type: "object"
                    properties:
                      3:
                        type: "integer"
                        example: "10"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"
          
  /users:
    get:
      tags:
      - "Users"
      summary: "Returns all users data"
      responses:
        200:
          description: "Successful operation<br>If is_submit value is <br>0 means the user has not submitted<br> 1 means the user has submitted<br><br> For object in lessons and forced_lessons, <br> key is period <br> value is lessons_id <br>i.e. { period => lesson_id } "
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "string"
                  example: "140123"
                cn_name:
                  type: "string"
                  example: "和恶"
                class:
                  type: "string"
                  example: "高三理忠"
                gender:
                  type: "string"
                  example: "男"
                type:
                  type: "integer"
                  example: 1
                is_submit:
                  type: "boolean"
                  example : 0
                lessons:
                    type: "object"
                    properties:
                      1:
                        type: "integer"
                        example: "2"
                forced_lessons:
                    type: "object"
                    properties:
                      3:
                        type: "integer"
                        example: "10"

                  
                  
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"
          
  /user/lesson:
    get:
      tags:
      - "Users"
      summary: "Returns all lesson suitable for the current user"
      responses:
        200:
          description: "Successful operation<br>If is_submit value is <br>0 means the user has not submitted<br> 1 means the user has submitted<br><br> For object in lessons and forced_lessons, <br> key is period <br> value is lessons_id <br>i.e. { period => lesson_id } "
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "string"
                  example: "140123"
                cn_name:
                  type: "string"
                  example: "和恶"
                class:
                  type: "string"
                  example: "高三理忠"
                gender:
                  type: "string"
                  example: "男"
                type:
                  type: "integer"
                  example: 1
                is_submit:
                  type: "boolean"
                  example : 0
                lessons:
                    type: "object"
                    properties:
                      1:
                        type: "integer"
                        example: "2"
                forced_lessons:
                    type: "object"
                    properties:
                      3:
                        type: "integer"
                        example: "10"

                  
                  
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"
  
  /user/login:
    post:
      tags:
      - "Users"
      summary : "Login"
      parameters:
      - in: "body"
        name: "Body"
        description: "Login user"
        schema:
          type: "object"
          properties:
            id:
              type: "integer"
              example: "140145"
            ic:
              type: "string"
              example: "123456-78-1234"

      responses:
        200:
          description: "Successful logged in"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"

  /user/logout:
    post:
      tags:
      - "Users"
      summary : "Logout"
              
      responses:
        200:
          description: "Successful logged out"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"
          
  /user/submit:
    post:
      tags:
      - "Users"
      summary : "submit lessons selection"
      parameters:
      - in: "body"
        name: "Body"
        description: "Edit user <br> provide lesson_id in the array"
        schema:
          type: "object"
          properties:
            lessons:
              type: "array"
              items:
                type: "integer"
              example: [3,2,1]
          
          
      responses:
        200:
          description: "Successful operation"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"

  /user/{userId}:
    put:
      tags:
      - "Users"
      summary: "Edit user"
      parameters:
      - name: "userId"
        in: "path"
        description: "ID of user to edit"
        required: true
        type: "integer"
      - in: "body"
        name: "Body"
        description: "Edit user"
        schema:
          type: "object"
          properties:
            id:
              type: "string"
              example: "150142"
            cn_name:
              type: "string"
              example: "常常"
            ic:
              type: "string"
              example: "123456-78-1234"
            gender:
              type: "string"
              example: "男"
            class_id:
              type: "integer"
              example: 1
            type:
              type: "integer"
              example: 1
      responses:
        200:
          description: "Successful operation"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"
    delete:
      tags:
      - "Users"
      summary: "Delete user"
      parameters:
      - name: "userId"
        in: "path"
        description: "ID of user to delete"
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful operation"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"

  /class:
    post:
      tags:
      - "Class"
      summary: "Create new class"
      parameters:
      - in: "body"
        name: "Body"
        schema:
          type: "object"
          properties:
            cn_name:
              type: "string"
              example: "2慧"
            en_name:
              type: "string"
              example: "2hui"
  
      responses:
        200:
          description: "Successful operation"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"

    get:
      tags:
      - "Class"
      summary: "Get all class data"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "integer"
                  example: 1
                cn_name:
                  type: "string"
                  example: "2慧"
                en_name:
                  type: "string"
                  example: "2hui"
        401:  
          description: "Unauthorized"
        400:
          description: "Validation Error"

  /class/{classId}:
    put:
      tags:
      - "Class"
      summary: "Edit class"
      parameters:
      - name: "classId"
        in: "path"
        description: "ID of user to edit"
        required: true
        type: "integer"
      - in: "body"
        name: "Body"
        schema:
          type: "object"
          properties:
            cn_name:
              type: "string"
              example: "2慧"
            en_name:
              type: "string"
              example: "2hui"
  
      responses:
        200:
          description: "Successful operation"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"
      
    delete:
      tags:
      - "Class"
      summary: "Delete class"
      parameters:
      - name: "classId"
        in: "path"
        description: "ID of class to delete"
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful operation"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"
          
  /lesson:
    post:
      tags:
      - "Lessons"
      summary: "Create new lesson"
      parameters:
      - in: "body"
        name: "Body"
        description: "Create new lesson"
        schema:
          type: "object"
          properties:
            name:
              type: "string"
              example: "啊实打实的"
            location:
              type: "string"
              example: "光驱的"
            subject:
              type: "string"
              example: "体育处"
            limit:
              type: "integer"
              example: 30
            stream:
              type: "string"
              example: "文"
            gender:
              type: "string"
              example: "男"
            description:
              type: "string"
              example: "asdasd"
            period:
              type: "array"
              items:
                type: "integer"
              example : [1,2,3]
            year:
              type: "array"
              items:
                type: "integer"
              example : [1,4,5]
              
      responses:
        200:
          description: "Successful operation"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"

    get:
      tags:
      - "Lessons"
      summary: "Returns all lessons data"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "integer"
                  example: "1"
                name:
                  type: "string"
                  example: "啊实打实的"
                location:
                  type: "string"
                  example: "光驱的"
                subject:
                  type: "string"
                  example: "体育处"
                current:
                  type: "string"
                  example: 12
                  
                limit:
                  type: "integer"
                  example: 30
                stream:
                  type: "string"
                  example: "理"
                gender:
                  type: "string"
                  example: "男"
                description:
                  type: "string"
                  example: "asdasd"
                period:
                  type: "array"
                  items:
                    type: "integer"
                  example : [1,2,3]
                year:
                  type: "array"
                  items:
                    type: "integer"
                  example : [1,4,5]
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"
          
  /lessons:
    get:
      tags:
      - "Lessons"
      summary: "Returns all user associated with all lesson"
      parameters:
      - name: "lessonId"
        in: "path"
        description: "ID of lesson to get"
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "integer"
                  example: "1"
                name:
                  type: "string"
                  example: "啊实打实的"
                location:
                  type: "string"
                  example: "光驱的"
                subject:
                  type: "string"
                  example: "体育处"
                current:
                  type: "string"
                  example: 12
                limit:
                  type: "integer"
                  example: 30
                stream:
                  type: "string"
                  example: "理"
                gender:
                  type: "string"
                  example: "男"
                description:
                  type: "string"
                  example: "asdasd"
                period:
                  type: "array"
                  items:
                    type: "integer"
                  example : [1,2,3]
                year:
                  type: "array"
                  items:
                    type: "integer"
                  example : [1,4,5]
                user:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      id:
                        type: "string"
                        example: "140123"
                      cn_name:
                        type: "string"
                        example: "和恶"
                      gender:
                        type: "string"
                        example: "男"
                      class:
                        type: "string"
                        example: "高三理忠"
                
                
                
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"
    
  
  /lesson/{lessonId}:
    get:
      tags:
      - "Lessons"
      summary: "Returns all user associated with the lesson"
      parameters:
      - name: "lessonId"
        in: "path"
        description: "ID of lesson to get"
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                id:
                  type: "string"
                  example: "140123"
                cn_name:
                  type: "string"
                  example: "和恶"
                gender:
                  type: "string"
                  example: "男"
                class:
                  type: "string"
                  example: "高三理忠"
                
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"
    put:
      tags:
      - "Lessons"
      summary: "Edit lesson"
      parameters:
      - name: "lessonId"
        in: "path"
        description: "ID of lesson to edit"
        required: true
        type: "integer"
      - in: "body"
        name: "Body"
        description: "Create new lesson"
        schema:
          type: "object"
          properties:
            name:
              type: "string"
              example: "啊实打实的"
            location:
              type: "string"
              example: "光驱的"
            subject:
              type: "string"
              example: "体育处"
            limit:
              type: "integer"
              example: 30
            stream:
              type: "string"
              example: "理"
            gender:
              type: "string"
              example: "男"
            description:
              type: "string"
              example: "asdasd"
            period:
              type: "array"
              items:
                type: "integer"
              example : [1,2,3]
            year:
              type: "array"
              items:
                type: "integer"
              example : [1,4,5]
      responses:
        200:
          description: "Successful operation"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"
          
    delete:
      tags:
      - "Lessons"
      summary: "Delete lesson"
      parameters:
      - name: "lessonId"
        in: "path"
        description: "ID of lesson to delete"
        required: true
        type: "integer"
      responses:
        200:
          description: "Successful operation"
        401:
          description: "Unauthorized"
        400:
          description: "Validation Error"